version: "3.0"
services:
  order:
    image: ghcr.io/sbk-cloud-services/order-microservice:latest
    build:
      context: .
    links:
      - database
    ports:
      - "127.0.0.1:8080:8080"

  database:
    image: mariadb:latest
    volumes: 
      - database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 3ayYMPwCd2maT3yuPGS6dnY7XC4CRnvb
      MYSQL_DATABASE: order
      MYSQL_USER: order
      MYSQL_PASSWORD: 3ayYMPwCd2maT3yuPGS6dnY7XC4CRnvb
    ports:
      - "127.0.0.1:3306:3306"

  adminer:
    image: adminer:latest
    links:
      - database
    ports:
      - "127.0.0.1:8000:8080"

volumes: 
  database:
