version: "3.0"
services:
#  order:
#    build:
#      context: .
#      args:
#        m2: ${m2}
#    links:
#      - database
#    ports:
#      - "127.0.0.1:8080:8080"

  database:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 3ayYMPwCd2maT3yuPGS6dnY7XC4CRnvb
      MYSQL_DATABASE: order
      MYSQL_USER: order
      MYSQL_PASSWORD: 3ayYMPwCd2maT3yuPGS6dnY7XC4CRnvb
    ports:
      - "127.0.0.1:3306:3306"

  adminer:
    image: adminer:latest
    links:
      - database
    ports:
      - "127.0.0.1:8000:8080"
